/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bancopresentacion.GUI;

import bancoblue.bancodominio.Cliente;
import com.mycompany.banconegocio.ControladorNegocio;
import com.mycompany.bancopersistencia.dtos.ClienteDTO;
import com.mycompany.bancopersistencia.persistencia.PersistenciaException;
import static com.mycompany.bancopresentacion.GUI.registroUI.validarCodigoPostal;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Armenta Baca Jose Maria, Carlos Hiram Sanchez Meneses
 */
public class ajustesUI extends javax.swing.JFrame {

    ControladorNegocio cn = new ControladorNegocio();

    /**
     * Creates new form cuentaUI
     */
    public ajustesUI() {
        initComponents();
        mostrarDatosCliente();

    }

    String idCliente = Sesion.getIdCliente();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        regresarBtn = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        actualizarBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nombreTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        apellidoPaternoTxt = new javax.swing.JTextField();
        apellidoMaternoTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        contraTxt = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        codigoPostalTxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        ciudadTxt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        coloniaTxt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        calleTxt = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        numeroTxt = new javax.swing.JTextField();
        confirmarContraTxt = new javax.swing.JPasswordField();
        fechaSelected = new com.toedter.calendar.JDateChooser();
        contraAviso = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        usuarioTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(22, 66, 91));

        regresarBtn.setForeground(new java.awt.Color(255, 255, 255));
        regresarBtn.setText("Regresar");
        regresarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regresarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regresarBtnMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(22, 66, 91));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel2.setText("Actualiza tus datos");

        actualizarBtn.setBackground(new java.awt.Color(53, 129, 184));
        actualizarBtn.setForeground(new java.awt.Color(255, 255, 255));
        actualizarBtn.setText("Cambiar");
        actualizarBtn.setBorder(null);
        actualizarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        actualizarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actualizarBtnMouseClicked(evt);
            }
        });
        actualizarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(22, 66, 91));
        jLabel3.setText("Modifica tus datos");

        jLabel4.setText("Nombre");

        nombreTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(22, 66, 91)));

        jLabel6.setText("Apellido Paterno");

        jLabel7.setText("Apellido Materno");

        jLabel8.setText("Fecha Nacimiento");

        apellidoPaternoTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(22, 66, 91)));

        apellidoMaternoTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(22, 66, 91)));
        apellidoMaternoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoMaternoTxtActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(22, 66, 91));
        jLabel9.setText("Cambiar contraseña");

        jLabel10.setText("Contraseña");

        contraTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(22, 66, 91)));

        jLabel11.setText("Confimar contraseña");

        jLabel13.setText("Codigo Postal");

        codigoPostalTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(22, 66, 91)));

        jLabel14.setText("Ciudad");

        ciudadTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(22, 66, 91)));

        jLabel15.setText("Colonia");

        coloniaTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(22, 66, 91)));

        jLabel16.setText("Calle");

        calleTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(22, 66, 91)));

        jLabel17.setText("Num Ext");

        numeroTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(22, 66, 91)));

        confirmarContraTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(22, 66, 91)));
        confirmarContraTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                confirmarContraTxtKeyPressed(evt);
            }
        });

        fechaSelected.setDateFormatString("y-MM-dd");

        contraAviso.setForeground(new java.awt.Color(255, 0, 0));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(22, 66, 91));
        jLabel18.setText("Cambiar usuario");

        jLabel19.setText("Nombre Usuario");

        usuarioTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(22, 66, 91)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(usuarioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(contraTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(confirmarContraTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(calleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)
                                    .addComponent(coloniaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)
                                    .addComponent(codigoPostalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)))
                            .addComponent(jLabel9)
                            .addComponent(contraAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6)
                                    .addComponent(apellidoPaternoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(apellidoMaternoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechaSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 169, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(numeroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ciudadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(actualizarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(66, 66, 66))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoPostalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ciudadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidoPaternoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellidoMaternoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coloniaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(calleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numeroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fechaSelected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel18))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contraTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmarContraTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actualizarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuarioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contraAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(regresarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(621, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(regresarBtn)
                .addContainerGap(408, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void confirmarContraTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmarContraTxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmarContraTxtKeyPressed

    private void apellidoMaternoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoMaternoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoMaternoTxtActionPerformed
    /**
     * Actualiza la información del cliente con los datos ingresados en los
     * campos de la interfaz. Realiza validaciones de los campos y muestra
     * mensajes de advertencia en caso de campos incompletos o contraseñas no
     * coincidentes.
     *
     * @param evt El evento que desencadena la acción.
     */
    private void actualizarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarBtnActionPerformed
        
        
        
        String nombre = nombreTxt.getText();
        String apellidoPaterno = apellidoPaternoTxt.getText();
        String apellidoMaterno = apellidoMaternoTxt.getText();
        String codigoPostal = codigoPostalTxt.getText();
        String ciudad = ciudadTxt.getText();
        String colonia = coloniaTxt.getText();
        String calle = calleTxt.getText();
        String numero = numeroTxt.getText();
        String usuario = usuarioTxt.getText();
        String contra = contraTxt.getText();
        String confirmarContra = confirmarContraTxt.getText();
        Date fecha = fechaSelected.getDate();
        String fechaNacimiento = (fecha != null) ? new SimpleDateFormat("yyyy-MM-dd").format(fecha) : "Fecha no seleccionada";
        SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
        Date fechaActual = new Date();
        String fechaActualFormato = formatoFecha.format(fechaActual);
        // Validar si todos los campos están completos
        if (!validarCampos()) {
            JOptionPane.showMessageDialog(this, "Por favor, llena todos los campos.", "Campos incompletos", JOptionPane.WARNING_MESSAGE);
            return; // Sale del método si los campos no están llenos
        }
        // Validar si las contraseñas coinciden
        if (!validarContra()) {
            contraAviso.setText("Las contraseñas no coinciden");
            return;
        }
        
        if (!validarEdad(fecha)) {
            JOptionPane.showMessageDialog(this, "Es necesario que la persona sea mayor de edad para continuar con el registro.", "Menor de edad", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(!validarNombre(nombre)) {
            JOptionPane.showMessageDialog(this, "Formato de nombre incorrecto.", "Input error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(!validarApellido(apellidoMaterno)) {
            JOptionPane.showMessageDialog(this, "Formato de apellido materno incorrecto.", "Input error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(!validarApellido(apellidoPaterno)) {
            JOptionPane.showMessageDialog(this, "Formato de apellido paterno incorrecto.", "Input error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        
        if(!validarCodigoPostal(codigoPostal)) {
            JOptionPane.showMessageDialog(this, "Formato de codigo postal incorrecto.", "Input error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(!validarUsuario(usuario)) {
            JOptionPane.showMessageDialog(this, "Formato de usuario incorrecto.", "Input error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(!validarDireccion(calle, colonia, numero, ciudad)) {
            JOptionPane.showMessageDialog(this, "Formato de direccion incorrecto.", "Input error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Intentar modificar el cliente con la información proporcionada
        try {
            ClienteDTO cliente = new ClienteDTO(nombre, apellidoPaterno, apellidoMaterno, fechaNacimiento, usuario, contra, codigoPostal, ciudad, calle, colonia, numero);
            Cliente clienteModificado = cn.modifcarClientePorID(idCliente, cliente);
            // Verificar si el cliente se ha modificado correctamente
            if (clienteModificado != null) {
                JOptionPane.showMessageDialog(null, "El cliente ha sido actualizado correctamente.");
                limpiarCampos();
                clienteUI cUI = new clienteUI();
                cUI.setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo modificar el cliente.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (PersistenciaException ex) {
            // handle errors
        }

    }//GEN-LAST:event_actualizarBtnActionPerformed
    /**
     * Muestra la interfaz principal de cliente cuando se hace clic en el botón
     * "Regresar".
     *
     * @param evt El evento de clic del mouse.
     */
    private void regresarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresarBtnMouseClicked
        // TODO add your handling code here:
        clienteUI cUI = new clienteUI();
        cUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_regresarBtnMouseClicked

    private void actualizarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actualizarBtnMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_actualizarBtnMouseClicked
    /**
     * Muestra los datos del cliente actual en los campos de la interfaz.
     */
    private void mostrarDatosCliente() {
        System.out.println(idCliente);
        int idClienteInt = Integer.parseInt(idCliente);
        try {
            Cliente clienteActual = cn.buscarClientePorId(idClienteInt);

            if (clienteActual != null) {

                SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
                Date fechaNacimiento = formatoFecha.parse(clienteActual.getFechaNacimiento());

                nombreTxt.setText(clienteActual.getNombre());
                apellidoPaternoTxt.setText(clienteActual.getApellidoP());
                apellidoMaternoTxt.setText(clienteActual.getApellidoM());
                fechaSelected.setDate(fechaNacimiento);
                usuarioTxt.setText(clienteActual.getUsuario());
                codigoPostalTxt.setText(clienteActual.getCodigoPostal());
                ciudadTxt.setText(clienteActual.getCiudad());
                contraTxt.setText(clienteActual.getContraseña());
                confirmarContraTxt.setText(clienteActual.getContraseña());
                calleTxt.setText(clienteActual.getCalle());
                coloniaTxt.setText(clienteActual.getColonia());
                numeroTxt.setText(clienteActual.getNumero());
                // otros campos
            } else {
                // error
            }
        } catch (ParseException | PersistenciaException e) {
            // handle error
        }
    }

    /**
     * Valida que todos los campos de la interfaz estén llenos.
     *
     * @return true si todos los campos están llenos, false de lo contrario.
     */
    public boolean validarCampos() {
        // Validamos que ningún campo esté vacío o contenga solo espacios en blanco
        if (nombreTxt.getText().isBlank()
                || apellidoPaternoTxt.getText().isBlank()
                || apellidoMaternoTxt.getText().isBlank()
                || codigoPostalTxt.getText().isBlank()
                || ciudadTxt.getText().isBlank()
                || coloniaTxt.getText().isBlank()
                || calleTxt.getText().isBlank()
                || numeroTxt.getText().isBlank()
                || usuarioTxt.getText().isBlank()
                || contraTxt.getText().isBlank()
                || confirmarContraTxt.getText().isBlank()
                || fechaSelected == null) {
            // Si algún campo está vacío o solo contiene espacios en blanco, retorna falso
            return false;
        }
        // Si todos los campos tienen algún valor, retorna verdadero
        return true;
    }

    /**
     * Valida si las contraseñas ingresadas coinciden.
     *
     * @return true si las contraseñas coinciden, false de lo contrario.
     */
    public boolean validarContra() {

        String pwd = new String(contraTxt.getPassword());
        String confirmPwd = new String(confirmarContraTxt.getPassword());

        if (!pwd.equals(confirmPwd)) {
            return false; //Las contraseñas no coinciden
        }
        return true;

        //Las contraseñas coinciden
    }

    /**
     * Limpia el contenido de todos los campos de la interfaz y reinicia la
     * fecha seleccionada.
     */
    public void limpiarCampos() {
        // Limpiamos el contenido de cada campo de texto
        nombreTxt.setText("");
        apellidoPaternoTxt.setText("");
        apellidoMaternoTxt.setText("");
        codigoPostalTxt.setText("");
        ciudadTxt.setText("");
        coloniaTxt.setText("");
        calleTxt.setText("");
        numeroTxt.setText("");
        usuarioTxt.setText("");
        contraTxt.setText("");
        confirmarContraTxt.setText("");
        // También puedes limpiar otros campos si los tienes

        // Además, si estás utilizando JDateChooser para la fecha, puedes reiniciar su valor a null
        fechaSelected.setDate(null);
    }


    /**
     * Método para validar si el cliente es mayor de edad.
     *
     * @param fechaNacimiento La fecha de nacimiento del cliente.
     * @return true si el cliente es mayor de edad, false de lo contrario.
     */
    public boolean validarEdad(Date fechaNacimiento) {
        Date fechaActual = new Date();
        int edad = calcularEdad(fechaNacimiento, fechaActual);
        return edad >= 18;
    }

    /**
     * Método para calcular la edad a partir de la fecha de nacimiento y la
     * fecha actual.
     *
     * @param fechaNacimiento La fecha de nacimiento del cliente.
     * @param fechaActual La fecha actual.
     * @return La edad del cliente.
     */
    private int calcularEdad(Date fechaNacimiento, Date fechaActual) {
        long milisegundosFechaNacimiento = fechaNacimiento.getTime();
        long milisegundosFechaActual = fechaActual.getTime();
        long diferencia = milisegundosFechaActual - milisegundosFechaNacimiento;
        return (int) (diferencia / 1000 / 60 / 60 / 24 / 365.25);
    }

    /**
     * Realiza la validación del nombre.
     *
     * @param nombre El nombre a validar.
     * @return true si el nombre es válido, false de lo contrario.
     */
    public boolean validarNombre(String nombre) {
        // Validar que el nombre no esté vacío, contenga solo letras y no exceda la longitud máxima
        return nombre.length() <= 50;
    }

    /**
     * Realiza la validación del apellido.
     *
     * @param apellido El apellido a validar.
     * @return true si el apellido es válido, false de lo contrario.
     */
    public boolean validarApellido(String apellido) {
        // Validar que el apellido no esté vacío, contenga solo letras y no exceda la longitud máxima
        return !apellido.isEmpty() && apellido.matches("^[a-zA-Z]+$") && apellido.length() <= 50;
    }
    
    

    /**
     * Realiza la validación del código postal.
     *
     * @param codigoPostal El código postal a validar.
     * @return true si el código postal es válido, false de lo contrario.
     */
    public static boolean validarCodigoPostal(String codigoPostal) {
        // Validar que el código postal contenga solo dígitos y tenga la longitud correcta
        return codigoPostal.matches("^[0-9]{5}$");
    }

    /**
     * Realiza la validación del usuario.
     *
     * @param usuario El nombre de usuario a validar.
     * @return true si el usuario es válido, false de lo contrario.
     */
    public boolean validarUsuario(String usuario) {
        // Validar que el usuario no esté vacío y no exceda la longitud máxima
        return usuario.length() <= 50;
    }

    /**
     * Realiza la validación de la contraseña.
     *
     * @param contra La contraseña a validar.
     * @return true si la contraseña es válida, false de lo contrario.
     */
    public boolean validarContrasena(String contra) {
        // Validar que la contraseña no esté vacía y no exceda la longitud máxima
        return !contra.isEmpty() && contra.length() <= 50;
    }

    /**
     * Realiza la validación de la fecha de nacimiento.
     *
     * @param fecha La fecha de nacimiento a validar.
     * @return true si la fecha de nacimiento es válida, false de lo contrario.
     */
    public boolean validarFechaNacimiento(Date fecha) {
        // Puedes agregar la lógica de validación de edad aquí según tus requisitos
        // En este ejemplo, simplemente se valida que la fecha no sea nula
        return fecha != null;
    }
    
    
    /**
     * Realiza la validación del direccion.
     *
     * @param calle dir a validar.
     * @param colonia dir a validar.
     * @param numExterior dir a validar.
     * @param ciudad dir a validar.
     * @return true si el apellido es válido, false de lo contrario.
     */
    public boolean validarDireccion(String calle, String colonia, String numExterior, String ciudad) {
        // Validar que el apellido no esté vacío, contenga solo letras y no exceda la longitud máxima
        return  calle.length() <= 100
                &&  colonia.length() <= 100
                &&  ciudad.length() <= 100
                && !numExterior.matches("^[0-9]$") && numExterior.length() <= 8;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarBtn;
    private javax.swing.JTextField apellidoMaternoTxt;
    private javax.swing.JTextField apellidoPaternoTxt;
    private javax.swing.JTextField calleTxt;
    private javax.swing.JTextField ciudadTxt;
    private javax.swing.JTextField codigoPostalTxt;
    private javax.swing.JTextField coloniaTxt;
    private javax.swing.JPasswordField confirmarContraTxt;
    private javax.swing.JLabel contraAviso;
    private javax.swing.JPasswordField contraTxt;
    private com.toedter.calendar.JDateChooser fechaSelected;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JTextField numeroTxt;
    private javax.swing.JLabel regresarBtn;
    private javax.swing.JTextField usuarioTxt;
    // End of variables declaration//GEN-END:variables
}
