/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bancopresentacion.GUI;

import bancoblue.bancodominio.Cuenta;
import com.mycompany.banconegocio.ControladorNegocio;
import com.mycompany.bancopersistencia.persistencia.PersistenciaException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author carlo
 */
public class MisCuentasUI extends javax.swing.JFrame {
    ControladorNegocio cn = new ControladorNegocio();
    String usuario = Sesion.getUsuario();
    
    /**
     * Creates new form MisCuentasUI
     */
    public MisCuentasUI() {
        initComponents();
        actualizarCuentas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        canceladasComboBox = new javax.swing.JComboBox<>();
        activasComboBox = new javax.swing.JComboBox<>();
        cancelarBtn = new javax.swing.JButton();
        activarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 24)); // NOI18N
        jLabel4.setText("Mis cuentas");

        jLabel1.setText("Regresar");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(22, 66, 91));
        jLabel2.setText("Activas");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(22, 66, 91));
        jLabel3.setText("Canceladas");

        canceladasComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        canceladasComboBox.setForeground(new java.awt.Color(0, 102, 255));
        canceladasComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(22, 66, 91)));
        canceladasComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                canceladasComboBoxMouseClicked(evt);
            }
        });
        canceladasComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canceladasComboBoxActionPerformed(evt);
            }
        });

        activasComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        activasComboBox.setForeground(new java.awt.Color(0, 102, 255));
        activasComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(22, 66, 91)));
        activasComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                activasComboBoxMouseClicked(evt);
            }
        });
        activasComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activasComboBoxActionPerformed(evt);
            }
        });

        cancelarBtn.setText("Cancelar cuenta");
        cancelarBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cancelarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnActionPerformed(evt);
            }
        });

        activarBtn.setText("Activar cuenta");
        activarBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        activarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        activarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(activasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(canceladasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancelarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(activarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(330, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(activasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(canceladasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(activarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        clienteUI cUI = new clienteUI();
        cUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void canceladasComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canceladasComboBoxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_canceladasComboBoxMouseClicked

    private void canceladasComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canceladasComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_canceladasComboBoxActionPerformed

    private void activasComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_activasComboBoxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_activasComboBoxMouseClicked

    private void activasComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activasComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_activasComboBoxActionPerformed

    /**
     * Método ejecutado cuando se hace clic en el botón "Cancelar Cuenta".
     * Cancela la cuenta seleccionada si cumple con ciertas condiciones.
     *
     * @param evt El evento de acción asociado al clic del botón.
     */
    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnActionPerformed
        // TODO add your handling code here:
        String cuentaSelect = (String) activasComboBox.getSelectedItem();
        String[] partes = cuentaSelect.split(" ");
        String numeroCuenta;
        Cuenta cuentaCargada;
        if (partes.length >= 2) {
            numeroCuenta = partes[0].substring(1);
            cuentaCargada = cargarCuentaSeleccionada(numeroCuenta);
            int cuentaACancelar = cuentaCargada.getId_cuenta();
            try {
                if (!cn.cancelarCuentaPorId(cuentaACancelar)) {
                    JOptionPane.showMessageDialog(null, "La cuenta no tiene que contar con saldo. Retira el dinero primero", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Cuenta " + numeroCuenta + " cancelada.");
                }
                actualizarCuentas();
            } catch (PersistenciaException ex) {

                // handle error
            }
        }
    }//GEN-LAST:event_cancelarBtnActionPerformed

    /**
     * Método ejecutado cuando se hace clic en el botón "Activar Cuenta".
     * Activa la cuenta seleccionada si cumple con ciertas condiciones.
     *
     * @param evt El evento de acción asociado al clic del botón.
     */
    private void activarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activarBtnActionPerformed
        // TODO add your handling code here:
        String cuentaSelect = (String) canceladasComboBox.getSelectedItem();
        String[] partes = cuentaSelect.split(" ");
        String numeroCuenta;
        Cuenta cuentaCargada;
        if (partes.length >= 2) {
            numeroCuenta = partes[0].substring(1);
            cuentaCargada = cargarCuentaSeleccionada(numeroCuenta);
            int cuentaACancelar = cuentaCargada.getId_cuenta();
            try {
                cn.activarCuentaPorId(cuentaACancelar);
                actualizarCuentas();
            } catch (PersistenciaException ex) {
                
                // handle error
            }
        }
    }//GEN-LAST:event_activarBtnActionPerformed


    private void actualizarCuentas() {
        try {
            if (usuario != null) {
                String idCliente = cn.obtenerIdCliente(usuario);
                actualiarListaCuentas(idCliente);
                actualiarListaCuentasCanceladas(idCliente);
                Sesion.setIdCliente(idCliente);
            } else {
                System.out.println("usuario null");
            }

        } catch (PersistenciaException ex) {
            Logger.getLogger(clienteUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void actualiarListaCuentas(String id_cliente) {
        List<String> cuentas;
        try {
            cuentas = cn.obtenerCuentas(id_cliente);

            activasComboBox.removeAllItems();

            if (cuentas != null && !cuentas.isEmpty()) {
                for (String cuenta : cuentas) {
                    activasComboBox.addItem(cuenta);
                }
            }
        } catch (PersistenciaException ex) {
            Logger.getLogger(clienteUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void actualiarListaCuentasCanceladas(String id_cliente) {
        List<String> cuentas;
        try {
            cuentas = cn.obtenerCuentasCanceladas(id_cliente);

            canceladasComboBox.removeAllItems();

            if (cuentas != null && !cuentas.isEmpty()) {
                for (String cuenta : cuentas) {
                    canceladasComboBox.addItem(cuenta);
                }
            }
        } catch (PersistenciaException ex) {
            Logger.getLogger(MisCuentasUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private Cuenta cargarCuentaSeleccionada(String numeroCuenta) {
        try {
            Cuenta cuentaSeleccionada = cn.obtenerCuentaPorNumCuentas(numeroCuenta);
            return cuentaSeleccionada;
        } catch (PersistenciaException ex) {
            //handle err
            return null;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton activarBtn;
    private javax.swing.JComboBox<String> activasComboBox;
    private javax.swing.JComboBox<String> canceladasComboBox;
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
